language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux
ruby: 2.2.0
before_install:
  - echo $LANG
  - echo $LC_ALL
  #- if [ $TRAVIS_OS_NAME == linux ]; then sudo ./build/dependencies.sh; fi
  #- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./build.sh --cc=clang --cxx=clang++; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./build.sh --cc=clang-3.8 --cxx=clang++-3.8; fi
#after_success:
#  - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build_support.sh archive_codedb; fi
#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then ./scripts/deploy.sh release github website triggers; fi
#install: make get-deps

